[[permission]]
identifier = "allow-check-native-update"
description = "Enables the check_native_update command without any pre-configured scope."
commands.allow = ["check_native_update"]

[[permission]]
identifier = "deny-check-native-update"
description = "Denies the check_native_update command without any pre-configured scope."
commands.deny = ["check_native_update"]
